[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HiddenMarkovModels = "84ca31d5-effc-45e0-bfda-5a68cd981f47"

[compat]
Distributions = ">=0.25.118"
HiddenMarkovModels = ">=0.3.1"
julia = "1.6.0"
